version: "3"
services:
  grafana:
    image: grafana/grafana:7.2.0 
    restart: always
    depends_on:
      - influxdb
    volumes:
      - /mnt/hdd/grafana/data:/var/lib/grafana 
      - /mnt/hdd/grafana/logs:/var/log/grafana 
      - /mnt/hdd/grafana/grafana.ini:/etc/grafana/grafana.ini
    ports:
      - "3000:3000"

  influxdb:
    image: influxdb:1.7 
    restart: always
    environment:
      INFLUXDB_DB: 'home'
    volumes:
      - /mnt/hdd/influxdb:/var/lib/influxdb 
  mDNS:
    image: ydkn/avahi:latest 
    restart: always
  nodeRed:
    image: nodered/node-red:1.1.3-minimal
    restart: always
    command: npm install --unsafe-perm --no-update-notifier --no-fund --only=production
    depends_on:
      - influxdb
    ports:
      - "80:1880"
    volumes:
      - /mnt/hdd/node-red:/data 
