version: "3"
services:
  influx:
    image: influxdb:1.7 
    restart: always
    volumes:
      - ./influxdb:/var/lib/influxdb 
  mDNS:
    image: ydkn/avahi:latest
  nodeRed:
    image: nodered/node-red:latest
    ports:
      - "80:1880"
    volumes:
      - /home/mrded/.node-red:/data
