version: "3"
services:
  grafana:
    image: grafana/grafana:7.2.0 
    restart: always
    depends_on:
      - influxdb
    volumes:
      - /mnt/hdd/grafana/data:/var/lib/grafana 
      - /mnt/hdd/grafana/logs:/var/log/grafana 
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
    ports:
      - "3000:3000"
      
  docker-host:
    image: qoomon/docker-host:2.5.0
    cap_add: [ 'NET_ADMIN', 'NET_RAW' ]
    restart: on-failure

  prometheus:
    image: prom/prometheus:v2.22.0
    depends_on: [ docker-host ]
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - /mnt/hdd/prometheus/data:/prometheus

  influxdb:
    image: influxdb:1.7 
    restart: always
    environment:
      INFLUXDB_DB: 'home'
    volumes:
      - /mnt/hdd/influxdb/data:/var/lib/influxdb
      - /mnt/hdd/influxdb/backup:/tmp/backup

  mDNS:
    image: ydkn/avahi:latest 
    restart: always

  nodeRed:
    image: nodered/node-red:1.1.3-minimal
    restart: always
    command: npm install --unsafe-perm --no-update-notifier --no-fund --only=production
    depends_on:
      - influxdb
    ports:
      - "80:1880"
    volumes:
      - ./node-red:/data 
