version: "3"
services:
  influx:
    image: influxdb:1.7 
    restart: always
    volumes:
      - ./influxdb:/var/lib/influxdb 
  mDNS:
    image: ydkn/avahi:latest 
    restart: always
  nodeRed:
    image: nodered/node-red:1.1.3-minimal
    restart: always
    depends_on:
      - influx 
    ports:
      - "80:1880"
    volumes:
      - ./node-red:/data 
